name: "Check repository"
description: "Checks typos, code lints, formatting, doc, test"
inputs:
  features:
    description: "cargo feature to enable"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: "Cargo formatting"
      if: $${{ always() }}
      shell: bash
      run: cargo fmt --all -- --check

    - name: "Cargo clippy"
      if: $${{ always() }}
      shell: bash
      run: cargo clippy --locked --profile=test --all-targets --all-features

    - name: "Cargo doc"
      if: $${{ always() }}
      shell: bash
      env:
        RUSTDOCFLAGS: "-D warnings"
      run: cargo doc --locked --no-deps

    - name: "Cargo test"
      if: $${{ always() }}
      shell: bash
      run: cargo test --locked ${{ inputs.features }}
